export interface IBANCountryInfo {
  countryCode: string;
  countryName: string;
  length: number;
  bankCodeStart?: number;
  bankCodeEnd?: number;
  bankCodeLength?: number;
  accountNumberStart?: number;
  accountNumberEnd?: number;
  flag: string;
}

export const ibanCountryData: Record<string, IBANCountryInfo> = {
  AD: {
    countryCode: "AD",
    countryName: "Andorra",
    length: 24,
    bankCodeStart: 4,
    bankCodeEnd: 8,
    bankCodeLength: 4,
    accountNumberStart: 8,
    accountNumberEnd: 24,
    flag: "🇦🇩",
  },
  AE: {
    countryCode: "AE",
    countryName: "United Arab Emirates",
    length: 23,
    bankCodeStart: 4,
    bankCodeEnd: 7,
    bankCodeLength: 3,
    accountNumberStart: 7,
    accountNumberEnd: 23,
    flag: "🇦🇪",
  },
  AL: {
    countryCode: "AL",
    countryName: "Albania",
    length: 28,
    bankCodeStart: 4,
    bankCodeEnd: 7,
    bankCodeLength: 3,
    accountNumberStart: 7,
    accountNumberEnd: 28,
    flag: "🇦🇱",
  },
  AT: {
    countryCode: "AT",
    countryName: "Austria",
    length: 20,
    bankCodeStart: 4,
    bankCodeEnd: 9,
    bankCodeLength: 5,
    accountNumberStart: 9,
    accountNumberEnd: 20,
    flag: "🇦🇹",
  },
  AZ: {
    countryCode: "AZ",
    countryName: "Azerbaijan",
    length: 28,
    bankCodeStart: 4,
    bankCodeEnd: 8,
    bankCodeLength: 4,
    accountNumberStart: 8,
    accountNumberEnd: 28,
    flag: "🇦🇿",
  },
  BA: {
    countryCode: "BA",
    countryName: "Bosnia and Herzegovina",
    length: 20,
    bankCodeStart: 4,
    bankCodeEnd: 9,
    bankCodeLength: 5,
    accountNumberStart: 9,
    accountNumberEnd: 20,
    flag: "🇧🇦",
  },
  BE: {
    countryCode: "BE",
    countryName: "Belgium",
    length: 16,
    bankCodeStart: 4,
    bankCodeEnd: 7,
    bankCodeLength: 3,
    accountNumberStart: 7,
    accountNumberEnd: 16,
    flag: "🇧🇪",
  },
  BG: {
    countryCode: "BG",
    countryName: "Bulgaria",
    length: 22,
    bankCodeStart: 4,
    bankCodeEnd: 8,
    bankCodeLength: 4,
    accountNumberStart: 8,
    accountNumberEnd: 22,
    flag: "🇧🇬",
  },
  BH: {
    countryCode: "BH",
    countryName: "Bahrain",
    length: 22,
    bankCodeStart: 4,
    bankCodeEnd: 8,
    bankCodeLength: 4,
    accountNumberStart: 8,
    accountNumberEnd: 22,
    flag: "🇧🇭",
  },
  BR: {
    countryCode: "BR",
    countryName: "Brazil",
    length: 29,
    bankCodeStart: 4,
    bankCodeEnd: 12,
    bankCodeLength: 8,
    accountNumberStart: 12,
    accountNumberEnd: 29,
    flag: "🇧🇷",
  },
  BY: {
    countryCode: "BY",
    countryName: "Belarus",
    length: 28,
    bankCodeStart: 4,
    bankCodeEnd: 8,
    bankCodeLength: 4,
    accountNumberStart: 8,
    accountNumberEnd: 28,
    flag: "🇧🇾",
  },
  CH: {
    countryCode: "CH",
    countryName: "Switzerland",
    length: 21,
    bankCodeStart: 4,
    bankCodeEnd: 9,
    bankCodeLength: 5,
    accountNumberStart: 9,
    accountNumberEnd: 21,
    flag: "🇨🇭",
  },
  CR: {
    countryCode: "CR",
    countryName: "Costa Rica",
    length: 22,
    bankCodeStart: 4,
    bankCodeEnd: 8,
    bankCodeLength: 4,
    accountNumberStart: 8,
    accountNumberEnd: 22,
    flag: "🇨🇷",
  },
  CY: {
    countryCode: "CY",
    countryName: "Cyprus",
    length: 28,
    bankCodeStart: 4,
    bankCodeEnd: 8,
    bankCodeLength: 4,
    accountNumberStart: 8,
    accountNumberEnd: 28,
    flag: "🇨🇾",
  },
  CZ: {
    countryCode: "CZ",
    countryName: "Czech Republic",
    length: 24,
    bankCodeStart: 4,
    bankCodeEnd: 8,
    bankCodeLength: 4,
    accountNumberStart: 8,
    accountNumberEnd: 24,
    flag: "🇨🇿",
  },
  DE: {
    countryCode: "DE",
    countryName: "Germany",
    length: 22,
    bankCodeStart: 4,
    bankCodeEnd: 12,
    bankCodeLength: 8,
    accountNumberStart: 12,
    accountNumberEnd: 22,
    flag: "🇩🇪",
  },
  DK: {
    countryCode: "DK",
    countryName: "Denmark",
    length: 18,
    bankCodeStart: 4,
    bankCodeEnd: 8,
    bankCodeLength: 4,
    accountNumberStart: 8,
    accountNumberEnd: 18,
    flag: "🇩🇰",
  },
  DO: {
    countryCode: "DO",
    countryName: "Dominican Republic",
    length: 28,
    bankCodeStart: 4,
    bankCodeEnd: 8,
    bankCodeLength: 4,
    accountNumberStart: 8,
    accountNumberEnd: 28,
    flag: "🇩🇴",
  },
  EE: {
    countryCode: "EE",
    countryName: "Estonia",
    length: 20,
    bankCodeStart: 4,
    bankCodeEnd: 6,
    bankCodeLength: 2,
    accountNumberStart: 6,
    accountNumberEnd: 20,
    flag: "🇪🇪",
  },
  EG: {
    countryCode: "EG",
    countryName: "Egypt",
    length: 29,
    bankCodeStart: 4,
    bankCodeEnd: 8,
    bankCodeLength: 4,
    accountNumberStart: 8,
    accountNumberEnd: 29,
    flag: "🇪🇬",
  },
  ES: {
    countryCode: "ES",
    countryName: "Spain",
    length: 24,
    bankCodeStart: 4,
    bankCodeEnd: 8,
    bankCodeLength: 4,
    accountNumberStart: 8,
    accountNumberEnd: 24,
    flag: "🇪🇸",
  },
  FI: {
    countryCode: "FI",
    countryName: "Finland",
    length: 18,
    bankCodeStart: 4,
    bankCodeEnd: 10,
    bankCodeLength: 6,
    accountNumberStart: 10,
    accountNumberEnd: 18,
    flag: "🇫🇮",
  },
  FO: {
    countryCode: "FO",
    countryName: "Faroe Islands",
    length: 18,
    bankCodeStart: 4,
    bankCodeEnd: 8,
    bankCodeLength: 4,
    accountNumberStart: 8,
    accountNumberEnd: 18,
    flag: "🇫🇴",
  },
  FR: {
    countryCode: "FR",
    countryName: "France",
    length: 27,
    bankCodeStart: 4,
    bankCodeEnd: 9,
    bankCodeLength: 5,
    accountNumberStart: 9,
    accountNumberEnd: 27,
    flag: "🇫🇷",
  },
  GB: {
    countryCode: "GB",
    countryName: "United Kingdom",
    length: 22,
    bankCodeStart: 4,
    bankCodeEnd: 10,
    bankCodeLength: 6,
    accountNumberStart: 10,
    accountNumberEnd: 22,
    flag: "🇬🇧",
  },
  GE: {
    countryCode: "GE",
    countryName: "Georgia",
    length: 22,
    bankCodeStart: 4,
    bankCodeEnd: 6,
    bankCodeLength: 2,
    accountNumberStart: 6,
    accountNumberEnd: 22,
    flag: "🇬🇪",
  },
  GI: {
    countryCode: "GI",
    countryName: "Gibraltar",
    length: 23,
    bankCodeStart: 4,
    bankCodeEnd: 8,
    bankCodeLength: 4,
    accountNumberStart: 8,
    accountNumberEnd: 23,
    flag: "🇬🇮",
  },
  GL: {
    countryCode: "GL",
    countryName: "Greenland",
    length: 18,
    bankCodeStart: 4,
    bankCodeEnd: 8,
    bankCodeLength: 4,
    accountNumberStart: 8,
    accountNumberEnd: 18,
    flag: "🇬🇱",
  },
  GR: {
    countryCode: "GR",
    countryName: "Greece",
    length: 27,
    bankCodeStart: 4,
    bankCodeEnd: 7,
    bankCodeLength: 3,
    accountNumberStart: 7,
    accountNumberEnd: 27,
    flag: "🇬🇷",
  },
  GT: {
    countryCode: "GT",
    countryName: "Guatemala",
    length: 28,
    bankCodeStart: 4,
    bankCodeEnd: 8,
    bankCodeLength: 4,
    accountNumberStart: 8,
    accountNumberEnd: 28,
    flag: "🇬🇹",
  },
  HR: {
    countryCode: "HR",
    countryName: "Croatia",
    length: 21,
    bankCodeStart: 4,
    bankCodeEnd: 11,
    bankCodeLength: 7,
    accountNumberStart: 11,
    accountNumberEnd: 21,
    flag: "🇭🇷",
  },
  HU: {
    countryCode: "HU",
    countryName: "Hungary",
    length: 28,
    bankCodeStart: 4,
    bankCodeEnd: 7,
    bankCodeLength: 3,
    accountNumberStart: 7,
    accountNumberEnd: 28,
    flag: "🇭🇺",
  },
  IE: {
    countryCode: "IE",
    countryName: "Ireland",
    length: 22,
    bankCodeStart: 4,
    bankCodeEnd: 10,
    bankCodeLength: 6,
    accountNumberStart: 10,
    accountNumberEnd: 22,
    flag: "🇮🇪",
  },
  IL: {
    countryCode: "IL",
    countryName: "Israel",
    length: 23,
    bankCodeStart: 4,
    bankCodeEnd: 7,
    bankCodeLength: 3,
    accountNumberStart: 7,
    accountNumberEnd: 23,
    flag: "🇮🇱",
  },
  IM: {
    countryCode: "IM",
    countryName: "Isle of Man",
    length: 22,
    bankCodeStart: 4,
    bankCodeEnd: 10,
    bankCodeLength: 6,
    accountNumberStart: 10,
    accountNumberEnd: 22,
    flag: "🇮🇲",
  },
  IQ: {
    countryCode: "IQ",
    countryName: "Iraq",
    length: 23,
    bankCodeStart: 4,
    bankCodeEnd: 7,
    bankCodeLength: 3,
    accountNumberStart: 7,
    accountNumberEnd: 23,
    flag: "🇮🇶",
  },
  IS: {
    countryCode: "IS",
    countryName: "Iceland",
    length: 26,
    bankCodeStart: 4,
    bankCodeEnd: 6,
    bankCodeLength: 2,
    accountNumberStart: 6,
    accountNumberEnd: 26,
    flag: "🇮🇸",
  },
  IT: {
    countryCode: "IT",
    countryName: "Italy",
    length: 27,
    bankCodeStart: 5,
    bankCodeEnd: 10,
    bankCodeLength: 5,
    accountNumberStart: 10,
    accountNumberEnd: 27,
    flag: "🇮🇹",
  },
  JO: {
    countryCode: "JO",
    countryName: "Jordan",
    length: 30,
    bankCodeStart: 4,
    bankCodeEnd: 8,
    bankCodeLength: 4,
    accountNumberStart: 8,
    accountNumberEnd: 30,
    flag: "🇯🇴",
  },
  KW: {
    countryCode: "KW",
    countryName: "Kuwait",
    length: 30,
    bankCodeStart: 4,
    bankCodeEnd: 8,
    bankCodeLength: 4,
    accountNumberStart: 8,
    accountNumberEnd: 30,
    flag: "🇰🇼",
  },
  KZ: {
    countryCode: "KZ",
    countryName: "Kazakhstan",
    length: 20,
    bankCodeStart: 4,
    bankCodeEnd: 7,
    bankCodeLength: 3,
    accountNumberStart: 7,
    accountNumberEnd: 20,
    flag: "🇰🇿",
  },
  LB: {
    countryCode: "LB",
    countryName: "Lebanon",
    length: 28,
    bankCodeStart: 4,
    bankCodeEnd: 8,
    bankCodeLength: 4,
    accountNumberStart: 8,
    accountNumberEnd: 28,
    flag: "🇱🇧",
  },
  LC: {
    countryCode: "LC",
    countryName: "Saint Lucia",
    length: 32,
    bankCodeStart: 4,
    bankCodeEnd: 8,
    bankCodeLength: 4,
    accountNumberStart: 8,
    accountNumberEnd: 32,
    flag: "🇱🇨",
  },
  LI: {
    countryCode: "LI",
    countryName: "Liechtenstein",
    length: 21,
    bankCodeStart: 4,
    bankCodeEnd: 9,
    bankCodeLength: 5,
    accountNumberStart: 9,
    accountNumberEnd: 21,
    flag: "🇱🇮",
  },
  LT: {
    countryCode: "LT",
    countryName: "Lithuania",
    length: 20,
    bankCodeStart: 4,
    bankCodeEnd: 9,
    bankCodeLength: 5,
    accountNumberStart: 9,
    accountNumberEnd: 20,
    flag: "🇱🇹",
  },
  LU: {
    countryCode: "LU",
    countryName: "Luxembourg",
    length: 20,
    bankCodeStart: 4,
    bankCodeEnd: 7,
    bankCodeLength: 3,
    accountNumberStart: 7,
    accountNumberEnd: 20,
    flag: "🇱🇺",
  },
  LV: {
    countryCode: "LV",
    countryName: "Latvia",
    length: 21,
    bankCodeStart: 4,
    bankCodeEnd: 8,
    bankCodeLength: 4,
    accountNumberStart: 8,
    accountNumberEnd: 21,
    flag: "🇱🇻",
  },
  MC: {
    countryCode: "MC",
    countryName: "Monaco",
    length: 27,
    bankCodeStart: 4,
    bankCodeEnd: 9,
    bankCodeLength: 5,
    accountNumberStart: 9,
    accountNumberEnd: 27,
    flag: "🇲🇨",
  },
  MD: {
    countryCode: "MD",
    countryName: "Moldova",
    length: 24,
    bankCodeStart: 4,
    bankCodeEnd: 6,
    bankCodeLength: 2,
    accountNumberStart: 6,
    accountNumberEnd: 24,
    flag: "🇲🇩",
  },
  ME: {
    countryCode: "ME",
    countryName: "Montenegro",
    length: 22,
    bankCodeStart: 4,
    bankCodeEnd: 7,
    bankCodeLength: 3,
    accountNumberStart: 7,
    accountNumberEnd: 22,
    flag: "🇲🇪",
  },
  MK: {
    countryCode: "MK",
    countryName: "North Macedonia",
    length: 19,
    bankCodeStart: 4,
    bankCodeEnd: 7,
    bankCodeLength: 3,
    accountNumberStart: 7,
    accountNumberEnd: 19,
    flag: "🇲🇰",
  },
  MN: {
    countryCode: "MN",
    countryName: "Mongolia",
    length: 20,
    bankCodeStart: 4,
    bankCodeEnd: 7,
    bankCodeLength: 3,
    accountNumberStart: 7,
    accountNumberEnd: 20,
    flag: "🇲🇳",
  },
  MR: {
    countryCode: "MR",
    countryName: "Mauritania",
    length: 27,
    bankCodeStart: 4,
    bankCodeEnd: 9,
    bankCodeLength: 5,
    accountNumberStart: 9,
    accountNumberEnd: 27,
    flag: "🇲🇷",
  },
  MT: {
    countryCode: "MT",
    countryName: "Malta",
    length: 31,
    bankCodeStart: 4,
    bankCodeEnd: 8,
    bankCodeLength: 4,
    accountNumberStart: 8,
    accountNumberEnd: 31,
    flag: "🇲🇹",
  },
  MU: {
    countryCode: "MU",
    countryName: "Mauritius",
    length: 30,
    bankCodeStart: 4,
    bankCodeEnd: 10,
    bankCodeLength: 6,
    accountNumberStart: 10,
    accountNumberEnd: 30,
    flag: "🇲🇺",
  },
  NL: {
    countryCode: "NL",
    countryName: "Netherlands",
    length: 18,
    bankCodeStart: 4,
    bankCodeEnd: 8,
    bankCodeLength: 4,
    accountNumberStart: 8,
    accountNumberEnd: 18,
    flag: "🇳🇱",
  },
  NO: {
    countryCode: "NO",
    countryName: "Norway",
    length: 15,
    bankCodeStart: 4,
    bankCodeEnd: 8,
    bankCodeLength: 4,
    accountNumberStart: 8,
    accountNumberEnd: 15,
    flag: "🇳🇴",
  },
  PK: {
    countryCode: "PK",
    countryName: "Pakistan",
    length: 24,
    bankCodeStart: 4,
    bankCodeEnd: 8,
    bankCodeLength: 4,
    accountNumberStart: 8,
    accountNumberEnd: 24,
    flag: "🇵🇰",
  },
  PL: {
    countryCode: "PL",
    countryName: "Poland",
    length: 28,
    bankCodeStart: 4,
    bankCodeEnd: 12,
    bankCodeLength: 8,
    accountNumberStart: 12,
    accountNumberEnd: 28,
    flag: "🇵🇱",
  },
  PS: {
    countryCode: "PS",
    countryName: "Palestine",
    length: 29,
    bankCodeStart: 4,
    bankCodeEnd: 8,
    bankCodeLength: 4,
    accountNumberStart: 8,
    accountNumberEnd: 29,
    flag: "🇵🇸",
  },
  PT: {
    countryCode: "PT",
    countryName: "Portugal",
    length: 25,
    bankCodeStart: 4,
    bankCodeEnd: 8,
    bankCodeLength: 4,
    accountNumberStart: 8,
    accountNumberEnd: 25,
    flag: "🇵🇹",
  },
  QA: {
    countryCode: "QA",
    countryName: "Qatar",
    length: 29,
    bankCodeStart: 4,
    bankCodeEnd: 8,
    bankCodeLength: 4,
    accountNumberStart: 8,
    accountNumberEnd: 29,
    flag: "🇶🇦",
  },
  RO: {
    countryCode: "RO",
    countryName: "Romania",
    length: 24,
    bankCodeStart: 4,
    bankCodeEnd: 8,
    bankCodeLength: 4,
    accountNumberStart: 8,
    accountNumberEnd: 24,
    flag: "🇷🇴",
  },
  RS: {
    countryCode: "RS",
    countryName: "Serbia",
    length: 22,
    bankCodeStart: 4,
    bankCodeEnd: 7,
    bankCodeLength: 3,
    accountNumberStart: 7,
    accountNumberEnd: 22,
    flag: "🇷🇸",
  },
  RU: {
    countryCode: "RU",
    countryName: "Russia",
    length: 33,
    bankCodeStart: 4,
    bankCodeEnd: 13,
    bankCodeLength: 9,
    accountNumberStart: 13,
    accountNumberEnd: 33,
    flag: "🇷🇺",
  },
  SA: {
    countryCode: "SA",
    countryName: "Saudi Arabia",
    length: 24,
    bankCodeStart: 4,
    bankCodeEnd: 8,
    bankCodeLength: 4,
    accountNumberStart: 8,
    accountNumberEnd: 24,
    flag: "🇸🇦",
  },
  SC: {
    countryCode: "SC",
    countryName: "Seychelles",
    length: 31,
    bankCodeStart: 4,
    bankCodeEnd: 10,
    bankCodeLength: 6,
    accountNumberStart: 10,
    accountNumberEnd: 31,
    flag: "🇸🇨",
  },
  SD: {
    countryCode: "SD",
    countryName: "Sudan",
    length: 18,
    bankCodeStart: 4,
    bankCodeEnd: 6,
    bankCodeLength: 2,
    accountNumberStart: 6,
    accountNumberEnd: 18,
    flag: "🇸🇩",
  },
  SE: {
    countryCode: "SE",
    countryName: "Sweden",
    length: 24,
    bankCodeStart: 4,
    bankCodeEnd: 7,
    bankCodeLength: 3,
    accountNumberStart: 7,
    accountNumberEnd: 24,
    flag: "🇸🇪",
  },
  SI: {
    countryCode: "SI",
    countryName: "Slovenia",
    length: 19,
    bankCodeStart: 4,
    bankCodeEnd: 8,
    bankCodeLength: 4,
    accountNumberStart: 8,
    accountNumberEnd: 19,
    flag: "🇸🇮",
  },
  SK: {
    countryCode: "SK",
    countryName: "Slovakia",
    length: 24,
    bankCodeStart: 4,
    bankCodeEnd: 8,
    bankCodeLength: 4,
    accountNumberStart: 8,
    accountNumberEnd: 24,
    flag: "🇸🇰",
  },
  SM: {
    countryCode: "SM",
    countryName: "San Marino",
    length: 27,
    bankCodeStart: 5,
    bankCodeEnd: 10,
    bankCodeLength: 5,
    accountNumberStart: 10,
    accountNumberEnd: 27,
    flag: "🇸🇲",
  },
  ST: {
    countryCode: "ST",
    countryName: "Sao Tome and Principe",
    length: 25,
    bankCodeStart: 4,
    bankCodeEnd: 8,
    bankCodeLength: 4,
    accountNumberStart: 8,
    accountNumberEnd: 25,
    flag: "🇸🇹",
  },
  SV: {
    countryCode: "SV",
    countryName: "El Salvador",
    length: 28,
    bankCodeStart: 4,
    bankCodeEnd: 8,
    bankCodeLength: 4,
    accountNumberStart: 8,
    accountNumberEnd: 28,
    flag: "🇸🇻",
  },
  TL: {
    countryCode: "TL",
    countryName: "East Timor",
    length: 23,
    bankCodeStart: 4,
    bankCodeEnd: 7,
    bankCodeLength: 3,
    accountNumberStart: 7,
    accountNumberEnd: 23,
    flag: "🇹🇱",
  },
  TN: {
    countryCode: "TN",
    countryName: "Tunisia",
    length: 24,
    bankCodeStart: 4,
    bankCodeEnd: 8,
    bankCodeLength: 4,
    accountNumberStart: 8,
    accountNumberEnd: 24,
    flag: "🇹🇳",
  },
  TR: {
    countryCode: "TR",
    countryName: "Turkey",
    length: 26,
    bankCodeStart: 4,
    bankCodeEnd: 9,
    bankCodeLength: 5,
    accountNumberStart: 9,
    accountNumberEnd: 26,
    flag: "🇹🇷",
  },
  UA: {
    countryCode: "UA",
    countryName: "Ukraine",
    length: 29,
    bankCodeStart: 4,
    bankCodeEnd: 10,
    bankCodeLength: 6,
    accountNumberStart: 10,
    accountNumberEnd: 29,
    flag: "🇺🇦",
  },
  VA: {
    countryCode: "VA",
    countryName: "Vatican City",
    length: 22,
    bankCodeStart: 4,
    bankCodeEnd: 7,
    bankCodeLength: 3,
    accountNumberStart: 7,
    accountNumberEnd: 22,
    flag: "🇻🇦",
  },
  VG: {
    countryCode: "VG",
    countryName: "British Virgin Islands",
    length: 24,
    bankCodeStart: 4,
    bankCodeEnd: 8,
    bankCodeLength: 4,
    accountNumberStart: 8,
    accountNumberEnd: 24,
    flag: "🇻🇬",
  },
  XK: {
    countryCode: "XK",
    countryName: "Kosovo",
    length: 20,
    bankCodeStart: 4,
    bankCodeEnd: 6,
    bankCodeLength: 2,
    accountNumberStart: 6,
    accountNumberEnd: 20,
    flag: "🇽🇰",
  },
};

export function getCountryInfo(countryCode: string): IBANCountryInfo | undefined {
  return ibanCountryData[countryCode.toUpperCase()];
}
